name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test django
      id: test-django
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 1
        max-score: 20
        setup-command: python manage.py test
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-DJANGO_RESULTS: "${{steps.test-django.outputs.result}}"
      with:
        runners: test-django
